#!/bin/bash

# Managed by Ansible

set -u
set -o pipefail

# --------------------------------------------------------------------------- #
#                       VARIABLE DEFINITIONS
# --------------------------------------------------------------------------- #

PATH=/usr/bin:/bin:/usr/sbin:/sbin

readonly _arg="${1:-x}"

# --------------------------------------------------------------------------- #
#                       FUNCTIONS
# --------------------------------------------------------------------------- #

errout() {
        local _msg="${0##*/} error: ${1}"
        printf '%s\n' "${_msg}" >&2
        exit 1
}

audit_input_arg() {
        local _reg='^([1-2]?[0-9]?[0-9]\.){3}[1-2]?[0-9]?[0-9]$'

        if [ "${_arg:-x}" == "x" ] ; then
                printf '%s\n' "Usage: ${0} ip_address" >&2
                exit 1
        fi

        if [ "${_arg}" == "0.0.0.0" ] ; then
                errout 'No way, 0.0.0.0 is too broad'
        fi

        if grep -Eq "${_reg}" <<<"${_arg}" ; then
                :
        else
                errout 'That does not look like an IP address'
        fi
}

log_info() {
        local _msg="${0##*/} info: ${1}"
        printf '%s\n' "${_msg}"
        logger -p local3.info "${_msg}"
}

confirm_needs_processing() {
        local _regex="val.*\"${_ip_regex}\""
        local _rc

        nft --json list set inet filter blackhole |
        jq . |
        grep -E "${_regex}" \
        > /dev/null
        _rc=${?}

        if [ ${_rc} -eq 0 ] ; then
                printf '%s\n' 'IP already being blocked'
                return ${_rc}
        elif [ ${_rc} -eq 1 ] ; then
                printf '%s\n' 'OK, let us block this'
                return ${_rc}
        else
                errout 'Problem quering firewall rules'
        fi
}

add_drop_rule() {
        nft add element inet filter blackhole "{ ${_ip} }"

        if [ ${?} -ne 0 ] ; then
                errout 'Problem adding rule'
        fi
}

# --------------------------------------------------------------------------- #
#                       MAIN LOGIC
# --------------------------------------------------------------------------- #

audit_input_arg

# Confirm the IP is not already being blocked
readonly _ip_regex="${_arg//./\\.}"
confirm_needs_processing

if [ ${?} -eq 1 ] ; then
        readonly _ip="${_arg}"
        add_drop_rule
        log_info "IP ${_ip} filtered"
fi

exit 0
